core: url mirror match support
Signed-off-by: sunrisepeak <speakshen@163.com>

diff --git a/bin/xlings b/bin/xlings
--- a/bin/xlings
+++ b/bin/xlings
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+trap "echo 'Ctrl+C or killed...'; exit 1" INT TERM
+
 export XLINGS_HOME_DIR=/home/xlings
 
 if [ "$(uname)" == "Darwin" ]; then
@@ -23,5 +25,12 @@ if [ "$UID" -eq 0 ]; then
     export XMAKE_ROOT=y
 fi
 
-cd $XLINGS_DIR/core
+cd "$XLINGS_DIR/core" || {
+  echo "xlings: error: file corrupt, please reinstall xlings..."
+  echo ""
+  echo -e "\tcurl -fsSL https://d2learn.org/xlings-install.sh | bash"
+  echo ""
+  exit 1
+}
+
 xmake xlings $XLINGS_RUN_DIR "$@"
